// NIST CSF 2.0 Function configuration with official colors

export const NIST_FUNCTIONS = [
  {
    fn: "gv",
    prefix: "GV",
    name: "GOVERN",
    nameTh: "การกำกับดูแล",
    desc: "กลยุทธ์ ความคาดหวัง และนโยบายด้านความมั่นคงปลอดภัยไซเบอร์ขององค์กร",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-500",
    icon: "🏛️",
    categories: {
      "GV.OC": "Organizational Context",
      "GV.RM": "Risk Management Strategy",
      "GV.RR": "Roles, Responsibilities & Authorities",
      "GV.PO": "Policy",
      "GV.OV": "Oversight",
      "GV.SC": "Supply Chain Risk Management",
    },
  },
  {
    fn: "id",
    prefix: "ID",
    name: "IDENTIFY",
    nameTh: "การระบุ",
    desc: "ทำความเข้าใจความเสี่ยงด้านไซเบอร์ในปัจจุบันขององค์กร",
    gradient: "from-blue-600 to-indigo-700",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    badge: "bg-blue-100 text-blue-700",
    bar: "bg-blue-500",
    icon: "🔍",
    categories: {
      "ID.AM": "Asset Management",
      "ID.RA": "Risk Assessment",
      "ID.IM": "Improvement",
    },
  },
  {
    fn: "pr",
    prefix: "PR",
    name: "PROTECT",
    nameTh: "การป้องกัน",
    desc: "มาตรการปกป้องเพื่อบริหารจัดการความเสี่ยงด้านไซเบอร์",
    gradient: "from-emerald-600 to-green-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-500",
    icon: "🛡️",
    categories: {
      "PR.AA": "Identity Mgmt, Auth & Access Control",
      "PR.AT": "Awareness and Training",
      "PR.DS": "Data Security",
      "PR.PS": "Platform Security",
      "PR.IR": "Technology Infrastructure Resilience",
    },
  },
  {
    fn: "de",
    prefix: "DE",
    name: "DETECT",
    nameTh: "การตรวจจับ",
    desc: "ค้นหาและวิเคราะห์การโจมตีทางไซเบอร์ที่อาจเกิดขึ้น",
    gradient: "from-amber-500 to-yellow-600",
    light: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-700",
    badge: "bg-amber-100 text-amber-700",
    bar: "bg-amber-500",
    icon: "📡",
    categories: {
      "DE.CM": "Continuous Monitoring",
      "DE.AE": "Adverse Event Analysis",
    },
  },
  {
    fn: "rs",
    prefix: "RS",
    name: "RESPOND",
    nameTh: "การตอบสนอง",
    desc: "ดำเนินการตอบสนองต่อเหตุการณ์ด้านไซเบอร์ที่ตรวจพบ",
    gradient: "from-orange-500 to-red-600",
    light: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    badge: "bg-orange-100 text-orange-700",
    bar: "bg-orange-500",
    icon: "🚨",
    categories: {
      "RS.MA": "Incident Management",
      "RS.AN": "Incident Analysis",
      "RS.CO": "Incident Response Communication",
      "RS.MI": "Incident Mitigation",
    },
  },
  {
    fn: "rc",
    prefix: "RC",
    name: "RECOVER",
    nameTh: "การกู้คืน",
    desc: "กู้คืนสินทรัพย์และการดำเนินงานที่ได้รับผลกระทบจากเหตุการณ์",
    gradient: "from-teal-600 to-cyan-700",
    light: "bg-teal-50",
    border: "border-teal-200",
    text: "text-teal-700",
    badge: "bg-teal-100 text-teal-700",
    bar: "bg-teal-500",
    icon: "♻️",
    categories: {
      "RC.RP": "Incident Recovery Plan Execution",
      "RC.CO": "Incident Recovery Communication",
    },
  },
]

export type NistFunction = (typeof NIST_FUNCTIONS)[number]
