// NIST AI Risk Management Framework 1.0 — Core Functions configuration

export const AI_RMF_FUNCTIONS = [
  {
    fn: "govern",
    prefix: "GV",
    name: "GOVERN",
    nameTh: "การกำกับดูแล AI",
    desc: "วัฒนธรรม กระบวนการ นโยบาย และโครงสร้างองค์กรที่จำเป็นสำหรับการบริหารความเสี่ยง AI อย่างมีประสิทธิภาพ",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-500",
    icon: "🏛️",
    categories: {
      "GV-1": "AI Risk Management Policies",
      "GV-2": "Accountability & Workforce",
      "GV-3": "Organizational Culture",
      "GV-4": "Organizational Teams & Structure",
      "GV-5": "AI Supply Chain Risk",
      "GV-6": "Legal & Regulatory Compliance",
    },
  },
  {
    fn: "map",
    prefix: "MAP",
    name: "MAP",
    nameTh: "การระบุบริบทและความเสี่ยง AI",
    desc: "บริบทถูกสร้างขึ้น ความเสี่ยง AI ถูกระบุและจัดประเภท รวมถึงผลกระทบต่อผู้มีส่วนได้ส่วนเสีย",
    gradient: "from-blue-600 to-indigo-700",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    badge: "bg-blue-100 text-blue-700",
    bar: "bg-blue-500",
    icon: "🗺️",
    categories: {
      "MAP-1": "AI Context & Risk Tolerance",
      "MAP-2": "Risk Identification & Categorization",
      "MAP-3": "Impact Assessment",
      "MAP-4": "Third-party & Supply Chain Risk",
      "MAP-5": "Output Monitoring",
    },
  },
  {
    fn: "measure",
    prefix: "MS",
    name: "MEASURE",
    nameTh: "การวัดและประเมินความเสี่ยง AI",
    desc: "ความเสี่ยง AI ได้รับการวิเคราะห์ ประเมิน ติดตาม และวัดผล รวมถึงการทดสอบ TEVV และ Bias",
    gradient: "from-emerald-600 to-green-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-500",
    icon: "📊",
    categories: {
      "MS-1": "Measurement Methods & Approaches",
      "MS-2": "Testing, Evaluation & Validation (TEVV)",
      "MS-3": "Risk Tracking & Prioritization",
      "MS-4": "Feedback & Continuous Measurement",
    },
  },
  {
    fn: "manage",
    prefix: "MG",
    name: "MANAGE",
    nameTh: "การจัดการความเสี่ยง AI",
    desc: "ความเสี่ยง AI ที่ระบุได้รับการบริหารจัดการตามลำดับความสำคัญ ติดตามผล และปรับปรุงอย่างต่อเนื่อง",
    gradient: "from-orange-500 to-red-600",
    light: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    badge: "bg-orange-100 text-orange-700",
    bar: "bg-orange-500",
    icon: "⚙️",
    categories: {
      "MG-1": "Risk Treatment & Response Plans",
      "MG-2": "Incident Management",
      "MG-3": "Monitoring & Review",
      "MG-4": "Continuous Improvement",
    },
  },
]

export type AiRmfFunction = (typeof AI_RMF_FUNCTIONS)[number]
