// พ.ร.บ. คุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) — section configuration

export const PDPA_SECTIONS = [
  {
    section: "collection",
    name: "การเก็บรวบรวมข้อมูล",
    nameEn: "Data Collection",
    desc: "หลักเกณฑ์ ฐานทางกฎหมาย และข้อกำหนดในการเก็บรวบรวมข้อมูลส่วนบุคคล",
    gradient: "from-rose-600 to-pink-700",
    light: "bg-rose-50",
    border: "border-rose-200",
    text: "text-rose-700",
    badge: "bg-rose-100 text-rose-700",
    bar: "bg-rose-500",
    icon: "📥",
    refs: ["มาตรา 19", "มาตรา 20", "มาตรา 22", "มาตรา 23", "มาตรา 24", "มาตรา 26", "มาตรา 28"],
  },
  {
    section: "rights",
    name: "สิทธิของเจ้าของข้อมูล",
    nameEn: "Data Subject Rights",
    desc: "สิทธิ์ที่เจ้าของข้อมูลส่วนบุคคลมีต่อข้อมูลของตน รวมถึงการแจ้งและการตลาดตรง",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-500",
    icon: "🔐",
    refs: ["มาตรา 30", "มาตรา 31", "มาตรา 32", "มาตรา 35", "มาตรา 36", "มาตรา 41", "มาตรา 42", "มาตรา 43", "มาตรา 44"],
  },
  {
    section: "controller",
    name: "ผู้ควบคุมและความปลอดภัย",
    nameEn: "Controllers, Processors & Security",
    desc: "หน้าที่ของผู้ควบคุม ผู้ประมวลผลข้อมูล มาตรการรักษาความปลอดภัย และการโอนข้อมูลข้ามพรมแดน",
    gradient: "from-emerald-600 to-teal-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-500",
    icon: "🛡️",
    refs: ["มาตรา 37", "มาตรา 38", "มาตรา 39", "มาตรา 40"],
  },
  {
    section: "penalties",
    name: "บทลงโทษ",
    nameEn: "Penalties & Enforcement",
    desc: "โทษทางแพ่ง ทางอาญา และทางปกครองสำหรับการละเมิด พ.ร.บ. PDPA",
    gradient: "from-amber-500 to-orange-600",
    light: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-700",
    badge: "bg-amber-100 text-amber-700",
    bar: "bg-amber-500",
    icon: "⚖️",
    refs: ["มาตรา 45", "มาตรา 83", "มาตรา 86", "มาตรา 91"],
  },
]

export type PdpaSection = (typeof PDPA_SECTIONS)[number]
