// ISO/IEC 42001:2023 — AI Management System (AIMS) section configuration

export const ISO42_SECTIONS = [
  {
    section: "context",
    name: "บริบทและความเป็นผู้นำ",
    nameEn: "Context & Leadership",
    desc: "ทำความเข้าใจบริบทขององค์กร ผู้มีส่วนได้ส่วนเสีย ขอบเขต AIMS และความมุ่งมั่นของผู้นำ (Clauses 4–5)",
    gradient: "from-blue-600 to-indigo-700",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    badge: "bg-blue-100 text-blue-700",
    bar: "bg-blue-500",
    icon: "🏢",
    refs: ["4.1", "4.2", "4.3", "4.4", "5.1", "5.2", "5.3"],
  },
  {
    section: "planning",
    name: "การวางแผนและสนับสนุน",
    nameEn: "Planning & Support",
    desc: "ระบุความเสี่ยงและโอกาส กำหนดวัตถุประสงค์ จัดสรรทรัพยากร สร้างสมรรถนะและการสื่อสาร (Clauses 6–7)",
    gradient: "from-emerald-600 to-teal-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-500",
    icon: "📋",
    refs: ["6.1", "6.2", "7.1", "7.2", "7.3", "7.4", "7.5"],
  },
  {
    section: "operation",
    name: "การปฏิบัติงาน",
    nameEn: "Operation",
    desc: "วางแผนการปฏิบัติงาน ประเมินความเสี่ยง AI ดำเนินการจัดการความเสี่ยง และประเมินผลกระทบ (Clause 8)",
    gradient: "from-orange-500 to-amber-600",
    light: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    badge: "bg-orange-100 text-orange-700",
    bar: "bg-orange-500",
    icon: "⚙️",
    refs: ["8.1", "8.2", "8.3", "8.4"],
  },
  {
    section: "evaluation",
    name: "การประเมินและปรับปรุง",
    nameEn: "Evaluation & Improvement",
    desc: "ติดตามผลการดำเนินงาน ตรวจสอบภายใน ทบทวนโดยผู้บริหาร และปรับปรุง AIMS อย่างต่อเนื่อง (Clauses 9–10)",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-500",
    icon: "📈",
    refs: ["9.1", "9.2", "9.3", "10.1", "10.2"],
  },
]

export type Iso42Section = (typeof ISO42_SECTIONS)[number]
