// ISO/IEC 27001:2022 — Clauses 4–10 (ISMS Requirements) + Annex A

// ─── ISMS Clauses 4–10 ────────────────────────────────────────────────────────

export const ISO_CLAUSES = [
  {
    section: "clause4",
    clauseNum: "4",
    name: "Context of the Organization",
    nameTh: "บริบทขององค์กร",
    desc: "ทำความเข้าใจบริบทภายนอก-ภายใน ผู้มีส่วนได้ส่วนเสีย ขอบเขต ISMS",
    gradient: "from-blue-700 to-indigo-800",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    badge: "bg-blue-100 text-blue-700",
    bar: "bg-blue-600",
    icon: "🏛️",
    refs: ["4.1","4.2","4.3","4.4"],
  },
  {
    section: "clause5",
    clauseNum: "5",
    name: "Leadership",
    nameTh: "ความเป็นผู้นำ",
    desc: "ความมุ่งมั่นของผู้บริหาร นโยบาย IS บทบาทและความรับผิดชอบ",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-600",
    icon: "👔",
    refs: ["5.1","5.2","5.3"],
  },
  {
    section: "clause6",
    clauseNum: "6",
    name: "Planning",
    nameTh: "การวางแผน",
    desc: "การระบุและบำบัดความเสี่ยง IS วัตถุประสงค์ IS และการวางแผนการเปลี่ยนแปลง",
    gradient: "from-emerald-600 to-teal-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-600",
    icon: "📋",
    refs: ["6.1.1","6.1.2","6.1.3","6.2","6.3"],
  },
  {
    section: "clause7",
    clauseNum: "7",
    name: "Support",
    nameTh: "การสนับสนุน",
    desc: "ทรัพยากร สมรรถนะ การตระหนักรู้ การสื่อสาร และข้อมูลเอกสาร",
    gradient: "from-amber-500 to-orange-600",
    light: "bg-amber-50",
    border: "border-amber-200",
    text: "text-amber-700",
    badge: "bg-amber-100 text-amber-700",
    bar: "bg-amber-500",
    icon: "🔧",
    refs: ["7.1","7.2","7.3","7.4","7.5"],
  },
  {
    section: "clause8",
    clauseNum: "8",
    name: "Operation",
    nameTh: "การปฏิบัติงาน",
    desc: "การวางแผนและควบคุมการปฏิบัติงาน การประเมินและบำบัดความเสี่ยง IS",
    gradient: "from-rose-600 to-red-700",
    light: "bg-rose-50",
    border: "border-rose-200",
    text: "text-rose-700",
    badge: "bg-rose-100 text-rose-700",
    bar: "bg-rose-600",
    icon: "⚙️",
    refs: ["8.1","8.2","8.3"],
  },
  {
    section: "clause9",
    clauseNum: "9",
    name: "Performance Evaluation",
    nameTh: "การประเมินผลการดำเนินงาน",
    desc: "การติดตามและวัดผล การตรวจสอบภายใน การทบทวนโดยผู้บริหาร",
    gradient: "from-cyan-600 to-sky-700",
    light: "bg-cyan-50",
    border: "border-cyan-200",
    text: "text-cyan-700",
    badge: "bg-cyan-100 text-cyan-700",
    bar: "bg-cyan-600",
    icon: "📊",
    refs: ["9.1","9.2.1","9.2.2","9.3.1","9.3.2","9.3.3"],
  },
  {
    section: "clause10",
    clauseNum: "10",
    name: "Improvement",
    nameTh: "การปรับปรุง",
    desc: "การปรับปรุงอย่างต่อเนื่อง การระบุและแก้ไขความไม่สอดคล้อง",
    gradient: "from-fuchsia-600 to-pink-700",
    light: "bg-fuchsia-50",
    border: "border-fuchsia-200",
    text: "text-fuchsia-700",
    badge: "bg-fuchsia-100 text-fuchsia-700",
    bar: "bg-fuchsia-600",
    icon: "🔄",
    refs: ["10.1","10.2"],
  },
]

export type IsoClause = (typeof ISO_CLAUSES)[number]

// ─── Annex A sections ─────────────────────────────────────────────────────────

export const ISO_SECTIONS = [
  {
    section: "a5",
    prefix: "A.5",
    name: "Organisational Controls",
    nameTh: "มาตรการควบคุมด้านองค์กร",
    desc: "นโยบาย บทบาท ความรับผิดชอบ และกระบวนการที่กำหนดในระดับองค์กร",
    gradient: "from-blue-600 to-indigo-700",
    light: "bg-blue-50",
    border: "border-blue-200",
    text: "text-blue-700",
    badge: "bg-blue-100 text-blue-700",
    bar: "bg-blue-500",
    icon: "🏢",
    totalControls: 37,
  },
  {
    section: "a6",
    prefix: "A.6",
    name: "People Controls",
    nameTh: "มาตรการควบคุมด้านบุคลากร",
    desc: "การจัดการด้านทรัพยากรบุคคล การตรวจสอบประวัติ และการฝึกอบรมด้านความมั่นคงปลอดภัย",
    gradient: "from-emerald-600 to-green-700",
    light: "bg-emerald-50",
    border: "border-emerald-200",
    text: "text-emerald-700",
    badge: "bg-emerald-100 text-emerald-700",
    bar: "bg-emerald-500",
    icon: "👥",
    totalControls: 8,
  },
  {
    section: "a7",
    prefix: "A.7",
    name: "Physical Controls",
    nameTh: "มาตรการควบคุมด้านกายภาพ",
    desc: "ความมั่นคงปลอดภัยทางกายภาพของสถานที่ อุปกรณ์ และสภาพแวดล้อม",
    gradient: "from-orange-500 to-amber-600",
    light: "bg-orange-50",
    border: "border-orange-200",
    text: "text-orange-700",
    badge: "bg-orange-100 text-orange-700",
    bar: "bg-orange-500",
    icon: "🔒",
    totalControls: 14,
  },
  {
    section: "a8",
    prefix: "A.8",
    name: "Technological Controls",
    nameTh: "มาตรการควบคุมด้านเทคโนโลยี",
    desc: "มาตรการด้านเทคนิคเพื่อปกป้องระบบสารสนเทศ เครือข่าย และข้อมูล",
    gradient: "from-violet-600 to-purple-700",
    light: "bg-violet-50",
    border: "border-violet-200",
    text: "text-violet-700",
    badge: "bg-violet-100 text-violet-700",
    bar: "bg-violet-500",
    icon: "💻",
    totalControls: 34,
  },
]

export type IsoSection = (typeof ISO_SECTIONS)[number]
